### ISSUE TITLE
[BUG] Broken on KDE Plasma 6.3

### ISSUE THREAD

**Issue by claymorwan** [EliverLara/kde_controlcentre#16]
**Describe the bug**
I just updated to KDE Plasma 6.3 and it simply doesn't work anymore.

**To Reproduce**
1. Update to Plasma 6.3
2. Try opening the plasmoid

**Expected behavior**
To work as before the update

**Screenshots**

![Image](https://github.com/user-attachments/assets/e10beeba-d65d-4c24-9d2f-e106ac8ae190)

**Desktop (please complete the following information):**
 - KDE Plasma Version:  KDE Plasma 6.3.0
 - Distribution: Arch Linux 6.13.2-arch1-1
 - Qt Version: 6.8.2
 - KDE Frameworks Version: 6.10.0

**Have you installed the following dependencies? (Yes/No)**
 - `kdeplasma-addons`: Yes
 - `plasma-nm`: Yes
 - KDE ConnectYes

**Comment by EliverLara** [comment]
I've published a quick fix to get it working in plasma 6.3, please try updating the applet from kde widgets store or directly from the [kde-store](https://store.kde.org/p/2196105/)

**Comment by marek2001** [comment]
Still not working after dirctly downloading new version from kde-store.

![Image](https://github.com/user-attachments/assets/f96daed0-3729-43ae-ae22-0433c45b7ff6)

**Comment by mekta03** [comment]
After the update, you need to use the advice from @EliverLara [#15](https://github.com/EliverLara/kde-control-station/issues/15#issuecomment-2646859226) opening `krunner` and executing `plasmashell --replace`.

**Comment by marek2001** [comment]
Now i can confirm that it works!!! Thank you!!!
