### ISSUE TITLE
[BUG] The widget is not compatable with Plasma 6.4 (beta 2) and Plasma 6.5 (alpha)

### ISSUE THREAD

**Issue by pnedyalkov91** [EliverLara/kde_controlcentre#29]
**Describe the bug**
The widget is not compatable with Plasma 6.4 (beta 2) and Plasma 6.5 (alpha)

**To Reproduce**
1. Install the widget via "Get New Stuff" in Plasma 6.4 or Plasma 6.5

**Expected behavior**
The widiget works as expected.

**Screenshots**
![Image](https://github.com/user-attachments/assets/ab957c1d-a464-4b68-b274-17e6b352a698)

**Desktop (please complete the following information):**
Operating System: Arch Linux 
KDE Plasma Version: 6.3.91
KDE Frameworks Version: 6.14.0
Qt Version: 6.9.1
Kernel Version: 6.15.2-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-3230M CPU @ 2.60GHz
Memory: 12 GiB of RAM (11.6 GiB usable)
Graphics Processor 1: Mesa Intel® HD Graphics 4000
Graphics Processor 2: NVD7

**Have you installed the following dependencies? (Yes/No)**
 - `kdeplasma-addons`: - Yes
 - `plasma-nm`: - Yes
 - KDE Connect - Yes

**Additional context**
The following error is presented when I click on the widget:
file:///home//.local/share/plasma/plasmoids/KdeControlStation/contents/ui/main.qml:111:25: Type FullRepresentation unavailable

file:///home/pnedyalkov/.local/share/plasma/plasmoids/KdeControlStation/contents/ui/FullRepresentation.qml:49:5: Type Pages.NightLightPage unavailable

file:///home/pnedyalkov/.local/share/plasma/plasmoids/KdeControlStation/contents/ui/pages/NightLightPage.qml:205:5: NightLightControl is not a type

**Comment by jastreb** [comment]
Plasma 6.4 has released today and this exact same bug happened to me too on Fedora 42 KDE 6 Plasma. Exact same problem no need to copy it around.

**Comment by Gapoly** [comment]
Same here, I should have waited before upgrading. My desktop feels empty without that KDE control station

```
file:///home/norman/.local/share/plasma/plasmoids/KdeControlStation/contents/ui/main.qml:98:25: Type FullRepresentation unavailable

file:///home/norman/.local/share/plasma/plasmoids/KdeControlStation/contents/ui/FullRepresentation.qml:52:5: Type Pages.NightLightPage unavailable

file:///home/norman/.local/share/plasma/plasmoids/KdeControlStation/contents/ui/pages/NightLightPage.qml:205:5: NightLightControl is not a type
```

**Comment by aflawrence** [comment]
Same thing happend here. I am guessing some incompatibility with 6.4. This happned to me last fall as well when I updated.

**Comment by EliverLara** [comment]
Hi, thanks for reporting! I'm working on fixing this bug

**Comment by EliverLara** [comment]
I've fixed the issue, Could you please try updating your plasmoid from discover or by directly downloading from [kde-store](https://www.pling.com/p/2196105/)?

**Comment by jastreb** [comment]
> I've fixed the issue, Could you please try updating your plasmoid from discover or by directly downloading from [kde-store](https://www.pling.com/p/2196105/)?

appreciate the effort, however its still showing the same error after updating, also tried to install it manually same thing

```

file:///home/jastreb/.local/share/plasma/plasmoids/KdeControlStation/contents/ui/main.qml:111:25: Type FullRepresentation unavailable

file:///home/jastreb/.local/share/plasma/plasmoids/KdeControlStation/contents/ui/FullRepresentation.qml:49:5: Type Pages.NightLightPage unavailable

file:///home/jastreb/.local/share/plasma/plasmoids/KdeControlStation/contents/ui/pages/NightLightPage.qml:205:5: NightLightControl is not a type
```

**Comment by EliverLara** [comment]
Did you try completely removing and reinstalling the widget? another important step is reloading `plasmashell` by opening `krunner` and executing` plasmashell --replace`

**Comment by jastreb** [comment]
> Did you try completely removing and reinstalling the widget? another important step is reloading `plasmashell` by opening `krunner` and executing` plasmashell --replace`

restarting plasmashell didnt help I had to remove contents of `~/.cache/plasmashell/qmlcache/` and then restart plasma, that worked for me ` systemctl --user restart plasma-plasmashell `

`plasmashell --replace` gets stuck there are too many errors related to themes and widgets

for anyone following me, backup your qmlcache folder before doing this!

works now, thanks

_ps: removing and reinstalling doesnt work either, guess cache sticks around_

**Comment by sorecaffeine** [comment]
just uninstalled it ,logout then login and reinstall it,it works

**Comment by jastreb** [comment]
> just uninstalled it ,logout then login and reinstall it,it works

weird I even tried restarting in between didnt help, guess its me then 💯

**Comment by aflawrence** [comment]
Thanks for the quick fix! Deleted reinstalled and working as expected.

**Comment by DiabloCRP** [comment]
idk why, but update via discover dont fix problem, but manual update directly from store.kde.org is ok

**Comment by Gapoly** [comment]
I updated the plasmoid and it worked for a while, now it stuck looking like that and I tried to reinstall it.

![Image](https://github.com/user-attachments/assets/e1d5ae92-845a-43ef-b12c-135cdb95cede)

**Comment by radlfabs** [comment]
Just here to confirm, that 

1. uninstalling
2. clearing the cache under `~/.cache/plasmashell/qmlcache/` as described in https://github.com/EliverLara/kde-control-station/issues/29#issuecomment-2993254625
3. restarting via `systemctl --user restart plasma-plasmashell`  as described in https://github.com/EliverLara/kde-control-station/issues/29#issuecomment-2993254625
4. re-installing directly from the [kde-store](https://www.pling.com/p/2196105/)

solves the issue on my system:

CachyOS x86_64
Linux 6.15.3-2-cachyos
KDE Plasma 6.4.0
KWin (Wayland)
